apiVersion: v1
kind: Service
metadata:
  name: todo-in-memory
  labels:
    app: todo-in-memory
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: todo-in-memory
    tier: backend